### ISSUE TITLE
master.ymlとlocal.ymlのcheck以下が正しくマージされない。

### ISSUE THREAD

**Issue by sowa-snow** [SoftwareFoundationGroupAtKyotoU/automata#57]
正しく（以前）は、check.{defaut,report_id}.{build,test}まで入っていってマージしていたのですが、現在checkをマージするようになっています。
```
# master.yml
check:
  default:
    build:
      command: "echo hoge"
    test:
      run: "echo hoge"
# local.yml
check:
  default:
    test:
      run: "echo fuga"
```
これをマージしたときに正しくは
```
{check: {default: {build: {command: "echo hoge"}, test: {run: "echo fuga"}}}}}
```
になるはずですが、現在
```
{check: {default: {test: {run: "echo fuga"}}}}
```
になっています。

個人的にはlocal.ymlとかなくそう派。
